version: "3.9"
services:
  php:
    image: php
    container_name: "php"
    ports:
      - "8080:80"
    links:
      - mailhog
    stdin_open: true
    tty: true
  mailhog:
    image: mailhog/mailhog
    container_name: "mailhog"
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"